In [78]:
import numpy as np


class FullyConnected:
    def __init__(self, input_layer, hidden_layer: list, output_layer) -> None:
        self.hidden_layer = hidden_layer
        input_layer = input_layer
        output_layer = output_layer

        L = len(hidden_layer)

        parameters = {}

        parameters["w" + str(1)] = (
            np.random.randn(hidden_layer[0]["units"], input_layer.shape[0]) * 0.01
        )
        parameters["b" + str(1)] = np.ones((hidden_layer[0]["units"], 1))
        self.parameters["out" + str(1)] = np.ones((hidden_layer[0]["units"], 1))
        self.parameters["net" + str(1)] = np.ones((hidden_layer[0]["units"], 1))

        for i in range(1, len(hidden_layer)):
            self.parameters["w" + str(i + 1)] = (
                np.random.randn(hidden_layer[i - 1]["units"], hidden_layer[i]["units"])
                * 0.01
            )
            self.parameters["b" + str(i + 1)] = np.ones((hidden_layer[i]["units"], 1))
            self.parameters["out" + str(i + 1)] = np.ones((hidden_layer[i]["units"], 1))
            self.parameters["net" + str(i + 1)] = np.ones((hidden_layer[i]["units"], 1))

        self.parameters["c"] = 1
        self.derivatives = {}

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-1 * x))

    def feedforward(self, input_layer):
        """
        w = weight matrix [   ]
        x = value matrix [   ]
        b = bias
        """
        self.parameters["out0"] = input_layer

        for l in range(1, self.L + 1):
            self.parameters["net" + str(l)] = np.add(
                np.dot(
                    self.parameters["w" + str(l)], self.parameters["out" + str(l - 1)]
                ),
                self.parameters["b" + str(l)],
            )
            self.parameters["out" + str(l)] = self.sigmoid(
                self.parameters["net" + str(l)]
            )

    def calc_derivatives(self, y):
        # 1. output layer 쪽 미분계수 구하기
        # -(target_o - out_o) * out_o(1 - out_o) * out_h
        self.parameters["d_out" + str(self.L)] = -(
            y - self.parameters["out" + str(self.L)]
        )
        self.parameters["dw" + str(self.L)] = self.parameters["d_out" + str(self.L)] * self.parameters["out" + str(self.L)] * (1 - self.parameters["out" + str(self.L)]) * np.transpose([self.parameters["out" + str(self.L - 1)]])
        self.parameters["db" + str(self.L)] = self.parameters["d_out" + str(self.L)]

        # 2. hidden layer 쪽 미분계수 구하기

        for i in range(self.L-1, 1):
            self.parameters["d_out" + str(i)] = -(self.parameters["out" + str(i+1)] - self.parameters["out" + str(i)])
            self.parameters["dw" + str(i)] = self.parameters["d_out" + str(i)] * self.parameters["out" + str(i)] * (1 - self.parameters["out" + str(i)]) * self.parameters("w" + str(i)) * self.parameters["out" + str(i-1)] * (1 - )

    def backpropagation(self):
        pass

    def calc_cost(self, y):
        # mean square error
        self.parameters["c"] = (1 / len(y)) * np.sum(
            np.subtract(y, self.parameters["out" + str(self.L)]) ** 2
        )

    def optimization(self):
        pass


In [79]:
hidden_layer = [{"name": "1", "units": 2}, {"name": "1", "units": 2}]
input_layer = np.array([0.05, 0.1])
output_layer = []
fc = FullyConnected(input_layer, hidden_layer, output_layer)
print(fc.parameters)

fc.feedforward(input_layer)
print(fc.parameters)


{'w1': array([[0.00207523, 0.0006083 ],
       [0.00167595, 0.00515475]]), 'b1': array([[1.],
       [1.]]), 'out1': array([[1.],
       [1.]]), 'net1': array([[1.],
       [1.]]), 'w2': array([[-0.01819469, -0.00973964],
       [ 0.00288313,  0.0090881 ]]), 'b2': array([[1.],
       [1.]]), 'out2': array([[1.],
       [1.]]), 'net2': array([[1.],
       [1.]]), 'c': 1}
{'w1': array([[0.00207523, 0.0006083 ],
       [0.00167595, 0.00515475]]), 'b1': array([[1.],
       [1.]]), 'out1': array([[0.73109094, 0.73117639],
       [0.73109094, 0.73117639]]), 'net1': array([[1.00016459, 1.00059927],
       [1.00016459, 1.00059927]]), 'w2': array([[-0.01819469, -0.00973964],
       [ 0.00288313,  0.0090881 ]]), 'b2': array([[1.],
       [1.]]), 'out2': array([[0.72702437, 0.72702389],
       [0.73277585, 0.73277606]]), 'net2': array([[0.97957746, 0.97957508],
       [1.00875206, 1.00875309]]), 'c': 1, 'out0': array([0.05, 0.1 ])}


In [201]:
class Temp:
    def __init__(self, parameter) -> None:
        
        self.parameters = parameter
        self.derivatives = {}
        self.L = 2

    def sigmoid(self, x):
        return 1/(1 + np.exp(-x))
    
    def sigmoid_prime(self, x):
        return self.sigmoid(x)*(1.0 - self.sigmoid(x))

    def forward_propagate(self, input_layer):
        #Note that X here, is just one training example
        self.parameters['a0'] = input_layer
        
        #Calculate the activations for every layer l
        for l in range(1, self.L + 1):
            self.parameters['net' + str(l)] = np.add(np.dot(self.parameters['w' + str(l)], self.parameters['out' + str(l - 1)]), self.parameters['b' + str(l)])
            self.parameters['out' + str(l)] = self.sigmoid(self.parameters['net' + str(l)])
        
    def compute_cost(self, y):
        self.parameters["c"] = (1 / len(y)) * np.sum(
            np.subtract(y, self.parameters["out" + str(self.L)]) ** 2
        )

    def compute_derivatives(self, y):
        #Partial derivatives of the cost function with respect to z[L], W[L] and b[L]:        
        #dzL
        self.derivatives['dz' + str(self.L)] = self.parameters['out' + str(self.L)] - y
        #dWL
        self.derivatives['dW' + str(self.L)] = np.dot(self.derivatives['dz' + str(self.L)], np.transpose(self.parameters['out' + str(self.L - 1)]))
        #dbL
        self.derivatives['db' + str(self.L)] = self.derivatives['dz' + str(self.L)]

        #Partial derivatives of the cost function with respect to z[l], W[l] and b[l]
        for l in range(self.L-1, 0, -1):
            self.derivatives['dz' + str(l)] = np.dot(np.transpose(self.parameters['w' + str(l + 1)]), self.derivatives['dz' + str(l + 1)])*self.sigmoid_prime(self.parameters['net' + str(l)])
            self.derivatives['dW' + str(l)] = np.dot(self.derivatives['dz' + str(l)], np.transpose(self.parameters['out' + str(l - 1)]))
            self.derivatives['db' + str(l)] = self.derivatives['dz' + str(l)]

    def update_parameters(self, alpha):
        for l in range(1, self.L+1):
            self.parameters['w' + str(l)] -= alpha*self.derivatives['dW' + str(l)]
            # self.parameters['b' + str(l)] -= alpha*self.derivatives['db' + str(l)]
                

In [202]:
temp = Temp(fc.parameters)

In [203]:
temp.forward_propagate(np.array([0.05, 0.1]))
temp.parameters

{'w1': array([[0.14398594, 0.19398594],
        [0.24398594, 0.29398594]]),
 'b1': array([0.35]),
 'out1': array([0.59305229, 0.5966673 ]),
 'net1': array([0.37659789, 0.39159789]),
 'w2': array([[0.4 , 0.45],
        [0.5 , 0.55]]),
 'b2': array([0.6]),
 'out2': array([0.75133055, 0.7728884 ]),
 'net2': array([1.1057212 , 1.22469316]),
 'c': array([1.281179  , 0.26981799]),
 'out0': array([0.05, 0.1 ]),
 'd_out2': array([ 0.74136507, -0.21707153]),
 'dw2': array([[ 0.08216704, -0.02260254],
        [ 0.08266763, -0.02274024]]),
 'db2': array([ 0.74136507, -0.21707153]),
 'a0': array([0.05, 0.1 ])}

In [204]:
temp.compute_cost(np.array([0.1, 0.99]))

In [205]:
temp.compute_derivatives(np.array([0.1, 0.99]))


In [206]:
temp.derivatives["db1"] * 0.5

array([0.01833909, 0.0208994 ])

In [207]:
temp.update_parameters(0.5)

In [208]:
temp.parameters

{'w1': array([[0.14097904, 0.19097904],
        [0.24097904, 0.29097904]]),
 'b1': array([0.35]),
 'out1': array([0.59305229, 0.5966673 ]),
 'net1': array([0.37659789, 0.39159789]),
 'w2': array([[0.27163516, 0.32163516],
        [0.37163516, 0.42163516]]),
 'b2': array([0.6]),
 'out2': array([0.75133055, 0.7728884 ]),
 'net2': array([1.1057212 , 1.22469316]),
 'c': array([1.28105866, 0.26986754]),
 'out0': array([0.05, 0.1 ]),
 'd_out2': array([ 0.74136507, -0.21707153]),
 'dw2': array([[ 0.08216704, -0.02260254],
        [ 0.08266763, -0.02274024]]),
 'db2': array([ 0.74136507, -0.21707153]),
 'a0': array([0.05, 0.1 ])}

In [80]:

w1 = fc.parameters['w1']
w1 = np.array(([0.15, 0.2], [0.25, 0.3]))
fc.parameters['w1'] = w1
b1 = fc.parameters['b1']
b1 = np.array([0.35])
fc.parameters['b1'] = b1

w2 = fc.parameters['w2']
w2 = np.array(([0.4, 0.45], [0.5, 0.55]))
fc.parameters['w2'] = w2
b2 = fc.parameters['b2']
b2 = np.array([0.6])
fc.parameters['b2'] = b2

In [154]:
fc.parameters

{'w1': array([[0.15, 0.2 ],
        [0.25, 0.3 ]]),
 'b1': array([0.35]),
 'out1': array([0.59326999, 0.59688438]),
 'net1': array([0.3775, 0.3925]),
 'w2': array([[0.4 , 0.45],
        [0.5 , 0.55]]),
 'b2': array([0.6]),
 'out2': array([0.75136507, 0.77292847]),
 'net2': array([1.10590597, 1.2249214 ]),
 'c': 0.2983711087600027,
 'out0': array([0.05, 0.1 ]),
 'd_out2': array([ 0.74136507, -0.21707153]),
 'dw2': array([[ 0.08216704, -0.02260254],
        [ 0.08266763, -0.02274024]]),
 'db2': array([ 0.74136507, -0.21707153])}

In [82]:
np.add(np.dot(w1, fc.parameters['out0']), b1) 

array([0.3775, 0.3925])

In [83]:
fc.feedforward(input_layer)

net1 = fc.parameters['net1']
out1 = fc.parameters['out1']
net2 = fc.parameters['net2']
out2 = fc.parameters['out2']

In [84]:
fc.parameters

{'w1': array([[0.15, 0.2 ],
        [0.25, 0.3 ]]),
 'b1': array([0.35]),
 'out1': array([0.59326999, 0.59688438]),
 'net1': array([0.3775, 0.3925]),
 'w2': array([[0.4 , 0.45],
        [0.5 , 0.55]]),
 'b2': array([0.6]),
 'out2': array([0.75136507, 0.77292847]),
 'net2': array([1.10590597, 1.2249214 ]),
 'c': 1,
 'out0': array([0.05, 0.1 ])}

In [85]:
out1

array([0.59326999, 0.59688438])

In [86]:
y = np.array([0.01, 0.99])

In [87]:
-(y - out2) *np.transpose([out2]) * np.array([1-out2]) * out1

array([[ 0.08216704, -0.02210583],
       [ 0.08452515, -0.02274024]])

In [94]:
-(y - out2) *(out2 * (1-out2)) * np.transpose([out1])


array([[ 0.08216704, -0.02260254],
       [ 0.08266763, -0.02274024]])

In [89]:
fc.calc_derivatives(y)

In [96]:
fc.calc_cost(y)

In [97]:
fc.parameters

{'w1': array([[0.15, 0.2 ],
        [0.25, 0.3 ]]),
 'b1': array([0.35]),
 'out1': array([0.59326999, 0.59688438]),
 'net1': array([0.3775, 0.3925]),
 'w2': array([[0.4 , 0.45],
        [0.5 , 0.55]]),
 'b2': array([0.6]),
 'out2': array([0.75136507, 0.77292847]),
 'net2': array([1.10590597, 1.2249214 ]),
 'c': 0.2983711087600027,
 'out0': array([0.05, 0.1 ]),
 'd_out2': array([ 0.74136507, -0.21707153]),
 'dw2': array([[ 0.08216704, -0.02260254],
        [ 0.08266763, -0.02274024]]),
 'db2': array([ 0.74136507, -0.21707153])}

In [107]:
d_out1 = -(y - out2)
dw1 = d_out1 * out2 * (1-out2) * w2


In [112]:
d_out1

array([ 0.74136507, -0.21707153])

In [113]:
out2 * (1-out2)

array([0.1868156 , 0.17551005])

In [114]:
d_out1 * out2 * (1-out2)

array([ 0.13849856, -0.03809824])

In [146]:
partial = np.dot(d_out1 * out2 * (1-out2), w2)
partial

array([0.03635031, 0.04137032])

In [148]:
outout = out1 * (1-out1)
outout

array([0.24130071, 0.24061342])

In [153]:
partial * outout

array([0.00877135, 0.00995425])

In [143]:
np.dot(d_out1 * out2 * (1-out2), np.array([[0.45], [0.55]]))
d_out1 * out2 * (1-out2)* np.array([[0.45, 0.55]])

array([[ 0.06232435, -0.02095403]])

In [140]:
np.dot(d_out1 * out2 * (1-out2), w2) * out1 * (1-out1) * np.transpose([fc.parameters['out0']])

array([[0.00043857, 0.00049771],
       [0.00087714, 0.00099543]])