In [236]:
import numpy as np


class FullyConnected:
    def __init__(self, input_layer, hidden_layer: list, output_layer) -> None:
        self.hidden_layer = hidden_layer
        input_layer = input_layer
        output_layer = output_layer

        self.L = len(hidden_layer)

        self.parameters = {}

        self.parameters["w" + str(1)] = (
            np.random.randn(hidden_layer[0]["units"], input_layer.shape[0]) * 0.01
        )
        self.parameters["b" + str(1)] = np.ones((hidden_layer[0]["units"], 1))
        self.parameters["out" + str(1)] = np.ones((hidden_layer[0]["units"], 1))
        self.parameters["net" + str(1)] = np.ones((hidden_layer[0]["units"], 1))

        for i in range(1, len(hidden_layer)):
            self.parameters["w" + str(i + 1)] = (
                np.random.randn(hidden_layer[i - 1]["units"], hidden_layer[i]["units"])
                * 0.01
            )
            self.parameters["b" + str(i + 1)] = np.ones((hidden_layer[i]["units"], 1))
            self.parameters["out" + str(i + 1)] = np.ones((hidden_layer[i]["units"], 1))
            self.parameters["net" + str(i + 1)] = np.ones((hidden_layer[i]["units"], 1))

        self.parameters["c"] = 1
        self.derivatives = {}

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-1 * x))

    def feedforward(self, input_layer):
        """
        w = weight matrix [   ]
        x = value matrix [   ]
        b = bias
        """
        self.parameters["out0"] = input_layer

        for l in range(1, self.L + 1):
            self.parameters["net" + str(l)] = np.add(
                np.dot(
                    self.parameters["w" + str(l)], self.parameters["out" + str(l - 1)]
                ),
                self.parameters["b" + str(l)],
            )
            self.parameters["out" + str(l)] = self.sigmoid(
                self.parameters["net" + str(l)]
            )

    def calc_derivatives(self, y):
        #Partial derivatives of the cost function with respect to z[L], W[L] and b[L]:        
        #Partial derivatives of the cost function with respect to z[l], W[l] and b[l]
        # 1. output layer 쪽 미분계수 구하기
        # -(target_o - out_o) * out_o(1 - out_o) * out_h
        #dzL
        self.derivatives['dz' + str(self.L)] = self.parameters['out' + str(self.L)] - y
        #dWL
        self.derivatives['dW' + str(self.L)] = self.parameters["dz" + str(self.L)] * self.parameters["out" + str(self.L)] * (1 - self.parameters["out" + str(self.L)]) * np.transpose([self.parameters["out" + str(self.L - 1)]])
        #dbL
        self.derivatives['db' + str(self.L)] = self.derivatives['dz' + str(self.L)]


        # 2. hidden layer 쪽 미분계수 구하기
        for l in range(self.L-1, 0, -1):
            self.derivatives['dz' + str(l)] = np.dot(np.transpose(self.parameters['w' + str(l + 1)]), self.derivatives['dz' + str(l + 1)])*self.sigmoid_prime(self.parameters['net' + str(l)])
            self.derivatives['dW' + str(l)] = np.dot(self.derivatives['dz' + str(l)], np.transpose(self.parameters['out' + str(l - 1)]))
            self.derivatives['db' + str(l)] = self.derivatives['dz' + str(l)]
            
    def backpropagation(self):
        pass

    def calc_cost(self, y):
        # mean square error
        self.parameters["c"] = 0.5 * np.sum(
            np.subtract(y, self.parameters["out" + str(self.L)]) ** 2
        )

    def optimization(self):
        pass


In [237]:
hidden_layer = [{"name": "1", "units": 2}, {"name": "1", "units": 2}]
input_layer = np.array([0.05, 0.1])
output_layer = []
fc = FullyConnected(input_layer, hidden_layer, output_layer)
print(fc.parameters)

fc.feedforward(input_layer)
print(fc.parameters)


{'w1': array([[ 0.01217507, -0.00025459],
       [ 0.00948438,  0.00181529]]), 'b1': array([[1.],
       [1.]]), 'out1': array([[1.],
       [1.]]), 'net1': array([[1.],
       [1.]]), 'w2': array([[-0.01631533, -0.00666241],
       [ 0.00213496,  0.00875436]]), 'b2': array([[1.],
       [1.]]), 'out2': array([[1.],
       [1.]]), 'net2': array([[1.],
       [1.]]), 'c': 1}
{'w1': array([[ 0.01217507, -0.00025459],
       [ 0.00948438,  0.00181529]]), 'b1': array([[1.],
       [1.]]), 'out1': array([[0.73117325, 0.73118749],
       [0.73117325, 0.73118749]]), 'net1': array([[1.00058329, 1.00065575],
       [1.00058329, 1.00065575]]), 'w2': array([[-0.01631533, -0.00666241],
       [ 0.00213496,  0.00875436]]), 'b2': array([[1.],
       [1.]]), 'out2': array([[0.72774256, 0.7277425 ],
       [0.73262112, 0.73262115]]), 'net2': array([[0.98319929, 0.98319896],
       [1.00796198, 1.00796214]]), 'c': 1, 'out0': array([0.05, 0.1 ])}


In [ ]:
class Temp:
    def __init__(self, parameter) -> None:
        
        self.parameters = parameter
        self.derivatives = {}
        self.L = 2

    def sigmoid(self, x):
        return 1/(1 + np.exp(-x))
    
    def sigmoid_prime(self, x):
        return self.sigmoid(x)*(1.0 - self.sigmoid(x))

    def forward_propagate(self, input_layer):
        #Note that X here, is just one training example
        self.parameters['a0'] = input_layer
        
        #Calculate the activations for every layer l
        for l in range(1, self.L + 1):
            self.parameters['net' + str(l)] = np.add(np.dot(self.parameters['w' + str(l)], self.parameters['out' + str(l - 1)]), self.parameters['b' + str(l)])
            self.parameters['out' + str(l)] = self.sigmoid(self.parameters['net' + str(l)])
        
    def compute_cost(self, y):
        self.parameters["c"] = (1 / len(y)) * np.sum(
            np.subtract(y, self.parameters["out" + str(self.L)]) ** 2
        )

    def compute_derivatives(self, y):
        #Partial derivatives of the cost function with respect to z[L], W[L] and b[L]:        
        #dzL
        self.derivatives['dz' + str(self.L)] = self.parameters['out' + str(self.L)] - y
        #dWL
        self.derivatives['dW' + str(self.L)] = self.parameters["dz" + str(self.L)] * self.parameters["out" + str(self.L)] * (1 - self.parameters["out" + str(self.L)]) * np.transpose([self.parameters["out" + str(self.L - 1)]])
        #dbL
        self.derivatives['db' + str(self.L)] = self.derivatives['dz' + str(self.L)]

        #Partial derivatives of the cost function with respect to z[l], W[l] and b[l]
        for l in range(self.L-1, 0, -1):
            self.derivatives['dz' + str(l)] = np.dot(np.transpose(self.parameters['w' + str(l + 1)]), self.derivatives['dz' + str(l + 1)])*self.sigmoid_prime(self.parameters['net' + str(l)])
            self.derivatives['dW' + str(l)] = np.dot(self.derivatives['dz' + str(l)], np.transpose(self.parameters['out' + str(l - 1)]))
            self.derivatives['db' + str(l)] = self.derivatives['dz' + str(l)]

    def update_parameters(self, alpha):
        for l in range(1, self.L+1):
            self.parameters['w' + str(l)] -= alpha*self.derivatives['dW' + str(l)]
            # self.parameters['b' + str(l)] -= alpha*self.derivatives['db' + str(l)]
                

In [ ]:
temp = Temp(fc.parameters)

In [238]:

w1 = fc.parameters['w1']
w1 = np.array(([0.15, 0.2], [0.25, 0.3]))
fc.parameters['w1'] = w1
b1 = fc.parameters['b1']
b1 = np.array([0.35])
fc.parameters['b1'] = b1

w2 = fc.parameters['w2']
w2 = np.array(([0.4, 0.45], [0.5, 0.55]))
fc.parameters['w2'] = w2
b2 = fc.parameters['b2']
b2 = np.array([0.6])
fc.parameters['b2'] = b2

In [243]:
fc.parameters

{'w1': array([[0.15, 0.2 ],
        [0.25, 0.3 ]]),
 'b1': array([0.35]),
 'out1': array([0.59326999, 0.59688438]),
 'net1': array([0.3775, 0.3925]),
 'w2': array([[0.4 , 0.45],
        [0.5 , 0.55]]),
 'b2': array([0.6]),
 'out2': array([0.75136507, 0.77292847]),
 'net2': array([1.10590597, 1.2249214 ]),
 'c': 0.2983711087600027,
 'out0': array([0.05, 0.1 ])}

In [ ]:
np.add(np.dot(w1, fc.parameters['out0']), b1) 

In [240]:
fc.feedforward(input_layer)

net1 = fc.parameters['net1']
out1 = fc.parameters['out1']
net2 = fc.parameters['net2']
out2 = fc.parameters['out2']

In [265]:
fc.derivatives = {}

In [266]:
L = 2
# fc.derivatives

# 1. output
fc.derivatives["da" + str(L)] = -(y - fc.parameters["out" + str(L)])
fc.derivatives["dz" + str(L)] = fc.parameters["out" + str(L)] * (1 - fc.parameters["out" + str(L)])
fc.derivatives["dw" + str(L)] = np.transpose([fc.derivatives["da" + str(L)] * fc.derivatives["dz" + str(L)]]) * fc.parameters["out" + str(L-1)]

fc.derivatives

{'da2': array([ 0.74136507, -0.21707153]),
 'dz2': array([0.1868156 , 0.17551005]),
 'dw2': array([[ 0.08216704,  0.08266763],
        [-0.02260254, -0.02274024]])}

In [269]:
# 2. hidden
for l in range(L-1, 0, -1):
    fc.derivatives["dw" + str(l)] = fc.derivatives["dw" + str(l+1)] * (1 / fc.parameters["out" + str(l)]) * fc.parameters["w" + str(l+1)] * fc.parameters["out" + str(l)] * (1 - fc.parameters["out" + str(l)]) * fc.parameters["out" + str(l-1)]

In [302]:
fc.derivatives["dw1"].T, fc.derivatives["dw1"]

(array([[ 0.0006684 , -0.00022983],
        [ 0.00149961, -0.00050418]]),
 array([[ 0.0006684 ,  0.00149961],
        [-0.00022983, -0.00050418]]))

In [298]:
da = np.transpose(fc.derivatives["da" + str(l+1)]) * fc.derivatives["dz" + str(l+1)] * fc.parameters["w" + str(l+1)]
dz = fc.parameters["out" + str(l)] * (1 - fc.parameters["out" + str(l)])
dw = np.transpose(da) * dz * fc.parameters["out" + str(0)]
da, dz, dw

(array([[ 0.05539942, -0.01714421],
        [ 0.06924928, -0.02095403]]),
 array([0.24130071, 0.24061342]),
 array([[ 0.0006684 ,  0.00166623],
        [-0.00020685, -0.00050418]]))

In [ ]:
y = np.array([0.01, 0.99])

In [ ]:
-(y - out2) *np.transpose([out2]) * np.array([1-out2]) * out1

In [ ]:
-(y - out2) *(out2 * (1-out2)) * np.transpose([out1])


In [ ]:
fc.calc_derivatives(y)

In [242]:
fc.calc_cost(y)

In [ ]:
fc.parameters

In [ ]:
d_out1 = -(y - out2)
dw1 = d_out1 * out2 * (1-out2) * w2


In [ ]:
d_out1

In [ ]:
out2 * (1-out2)

In [ ]:
d_out1 * out2 * (1-out2)

In [ ]:
partial = np.dot(d_out1 * out2 * (1-out2), w2)
partial

In [ ]:
outout = out1 * (1-out1)
outout

In [ ]:
partial * outout

In [ ]:
np.dot(d_out1 * out2 * (1-out2), np.array([[0.45], [0.55]]))
d_out1 * out2 * (1-out2)* np.array([[0.45, 0.55]])

In [ ]:
np.dot(d_out1 * out2 * (1-out2), w2) * out1 * (1-out1) * np.transpose([fc.parameters['out0']])

In [305]:

kernel_height, kernel_width = (3, 3)
filters = np.random.random(
    (8, 3, kernel_height, kernel_width)
)  # get filter든 뭐든 get_filter(filterNum=filterNum, size=width)
filters[0].shape

(3, 3, 3)